name: flutter_application
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # StateManagement
  flutter_bloc:
  tuple:
  freezed_annotation:
  # JsonParser
  json_annotation:

  # Http Client
  dio:

  #Svg Loader
  flutter_svg:

  # Local Persist
  shared_preferences:

  # Simple direct Service Locator
  get_it:

  # A collection of utilities to transform and manipulate streams.
  stream_transform: ^2.0.0

  responsive_framework: ^0.2.0

  google_fonts: ^4.0.3

  percent_indicator: ^4.2.2

  carousel_slider: ^4.2.1

  go_router: ^6.2.0

  #auth_nav
  auth_nav:
    git: https://github.com/dangngocduc/auth_nav

  oauth2_dio:
    git: https://github.com/dangngocduc/oauth2_dio

  # Collections and utilities functions and classes related to collections.
  collection: ^1.16.0

  intercom_flutter: ^7.6.6



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.0

# Config icon application
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true